apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myd
  name: myd
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myd
  type: NodePort
status:
  loadBalancer: {}
